env:
  IMAGE: bandsintown/nginx

steps:
  - label: ":docker: Build and Push v${VERSION}"
    if: build.env("VERSION") != "NA"
    plugins:
      - docker-compose#v5.2.0:
          cli-version: 1
          buildkit: false
          build: nginx
          push:
            - nginx:${IMAGE}:${VERSION}
            - nginx:${IMAGE}:${VERSION}-${BUILDKITE_COMMIT:0:7}

  - wait

  - label: ":docker: Tag as latest and Push v${VERSION}"
    if: build.env("VERSION_IS_LATEST") == "yes"
    plugins:
      - docker-compose#v5.2.0:
          cli-version: 1
          buildkit: false
          push:
            - nginx:${IMAGE}:latest
